### ISSUE TITLE
Can you give me some instructions about  your state variables and  state transfer function?

### ISSUE THREAD

**Issue by jylhaust** [karanchawla/GPS_INS_Fusion#1]
Thank you for sharing ! I have a question about your ekf algorithm. I don't know what state variables are you choose and how to get  the state transfer equation and measurement equation ? Can you give me some advice and papers about your algorithm ?

**Comment by karanchawla** [comment]
Hi, sure I'll update this over the weekend with the explanation of all the parameters, equations and references along with how to run the project. Let me know after that if something is not clear.

**Comment by karanchawla** [comment]
Hey I have now added the required instructions. Do let me know if something is not clear.
