### ISSUE TITLE
No example data Data.csv

### ISSUE THREAD

**Issue by DamonMIN** [karanchawla/GPS_INS_Fusion#2]
Can you share one example data as descripted in main.cpp? Thanks a lot.

**Comment by karanchawla** [comment]
Yes, I will upload it once I get home tonight.

**Comment by DamonMIN** [comment]
@karanchawla What's more,  the key data process function in main.cpp is commented out. It's really confused for a beginner in data funsion field. I think the code is a good meterial to learn the theory of data fusion. Please tell me how to call the main data fusion function in main.cpp.

**Comment by zzcczzcc** [comment]
hello,I download your code ,but it can not run.

**Comment by tingfenghanlei** [comment]
I can not find the example data as descripted in main.cpp. Have you uploaded it? If not ,please upload it , thanks.

**Comment by 863217373** [comment]
After look over previous comments, it seems like that the "Data.csv" has been updated. but I can't find it. Can you share the data with as again. thanks a lot.

**Comment by liyuebit** [comment]
Hello, thank you for sharing. And I have some questions.
(1)The key data process function in main.cpp is commented out,  please tell me how to call the main data fusion function in main.cpp.
(2)What data does the algorithm need?I guess, GPS: PosionXYZ(In which reference frame?), VelXYZ(In which reference frame?). IMU:accXYZ, gyrXYZ, and other data? 
(3)Can you upload some example data please?
Look forward to your reply, thank you very much.

**Comment by karanchawla** [comment]
Added `data.csv` file. 

All the data needs to be provided in the frame of reference of the vehicle, check out the diagram shown in the Readme. 

Yes, this repository doesn't show how to run the library but you would call the main GPSINS class in a loop as your imu data comes in.

**Comment by karanchawla** [comment]
Added.
